# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/health
Accept: application/json

###

POST http://127.0.0.1:8000/best-comp
Content-Type: application/json
Accept: application/json

< data/players_0.json

###

POST http://127.0.0.1:8000/best-comp
Content-Type: application/json
Accept: application/json

< data/players_1.json

###

POST http://127.0.0.1:8000/best-comp
Content-Type: application/json
Accept: application/json

< data/players_2.json

###

POST http://127.0.0.1:8000/best-comp
Content-Type: application/json
Accept: application/json

< data/players_3.json


###

POST http://127.0.0.1:8000/best-comp/top-n
Content-Type: application/json
Accept: application/json

< data/players_0.json

###

POST http://127.0.0.1:8000/best-comp/top-n
Content-Type: application/json
Accept: application/json

< data/players_1.json

###

POST http://127.0.0.1:8000/best-comp/top-n
Content-Type: application/json
Accept: application/json

< data/players_2.json

###

POST http://127.0.0.1:8000/best-comp/top-n
Content-Type: application/json
Accept: application/json

< data/players_3.json